### PR TITLE
0.3

### PR DESCRIPTION
**Pull request by adsick**
Hi, I want examples look a bit more fancy so I tried to add some code to Tree example
I am a beginner at programming and don't know for sure how Git works so I didn't push anything yet, can you advice me how can I help by contributing my code?
notice clamp fn definition after tree fn def in my code sample, I think it should be considered as default member of helpers in macroquad.

Here what it looks like:
`use macroquad::{Window, prelude::*};

fn tree(gl: &mut QuadGl, time: f64, deep: u32, angle: f32, tall: f32) {
    if deep >= 10 {
        return;
    }

    // we can use normal macroquad drawing API here
    draw_rectangle(-0.01 / 2., 0., 0.01, tall, GREEN);

    // and we can also modify internal macroquad render state with "gl" reference
    gl.push_model_matrix(glam::Mat4::from_translation(glam::vec3(0., tall, 0.)));

    // right leaf
    gl.push_model_matrix(glam::Mat4::from_rotation_z(angle + time.sin() as f32 * 0.1));
    tree(gl, time, deep + 1, angle * 0.7, tall * 0.8);
    gl.pop_model_matrix();

    // left leaf
    gl.push_model_matrix(glam::Mat4::from_rotation_z(
        -angle - time.cos() as f32 * 0.1,
    ));
    tree(gl, time, deep + 1, angle * 0.7, tall * 0.8);
    gl.pop_model_matrix();

    gl.pop_model_matrix();
}

//I'm not sure but it seems to me that it should be in some helpers of Macroquad
fn clamp(x: f32, low: f32, high: f32)->f32{
    match x{
        _ if x<low => low,
        _ if x>high => high,
        _ => x
    }
}

#[macroquad::main("Tree")]
async fn main() {
    let mut scale = 0.7; //good on 1920x1080 when fullscreen

    loop {
        let camera = Camera2D {
            zoom: vec2(1.*scale, scale*screen_width()/screen_height()), //fixed screen proportions
            target: vec2(0.0, 0.5),
            ..Default::default()
        };

        set_camera(camera);
        scale*= 1.0 + (mouse_wheel().1 as f32)/10.0; //modifying scale
        scale = clamp(scale, 0.02, 5.0); //making it not to go too far or too close
        //println!("{}", scale); //debug

        clear_background(BLUE);
        
        //draw_circle(0., 0., 0.03, GREEN); //initial position marker
        tree(unsafe { get_internal_gl().quad_gl }, get_time(), 0, 1., 0.3);

        next_frame().await
    }
}
`

### CODE REVIEW

**Comment by not-fl3** [comment]
>  notice clamp fn definition after tree fn def in my code sample, I think it should be considered as default member of helpers in macroquad.

I think `math` module may be a good place for `clamp`. 

But I would recommend to rebase your PR from master first - it is a little hard to review PR with 51 commits in it :)

**Comment by adsick** [comment]
Ok, sorry if I am looking like an idiot but be patient I... :)
So how should I do PR's to actually help?

**Comment by adsick** [comment]
Just found, that clamp is already f32 method, I had to expect that. But now I remember, that there is also vector clamp (and I don't see it inside of vec3.rs)
so I tried to write this, but it doesn't compile due to I dunno what)
 (code inside impl Vec3 after fn normalize() )

    ```#[inline]
    pub fn clamp(self, min: f32, max: f32)->Self{
        let len = self.length();
        let norm = self.normalize();
        if len < min {
            norm*min
        } 
        if len < max {
            self
        }
        
        norm*max
        ```

**Comment by vitvakatu** [comment]
@adsick Hello and thank you for your will to contribute.

First of all, you need to know some basics of Git and GitHub. There are plenty of tutorials in the internet, [Pro Git book](https://git-scm.com/book/en/v2) is available for free and is translated to many languages.

If you want to propose something, ask for new feature or ask any other question regarding this project, [issues](https://github.com/not-fl3/macroquad/issues) are the best tool for it. Just go ahead and open one.

If you want to actually make some changes to the code, you basically need to follow these steps:

1. Create a fork of repository. Use big `Fork` button on main repository page.
2. Clone your fork to your local machine using `git clone`
2. Choose a branch you want to make changes to. `master` is a good choice almost in every situation. Checkout to this branch using `git checkout`: `git checkout master`.
3. Create new branch with some unique name: `git checkout -b my_new_branch`
4. Make some changes to code
5. Commit them: `git commit -am "Description of my awesome changes"`
6. Push to your GitHub: `git push`. For the first time, you'll need `git push -u origin my_new_branch`.
7. Create new PR using [new PR button](https://github.com/not-fl3/macroquad/compare). At the top of the page, choose `compare across forks`, if it is available, than choose target and base branches so it looks like `base repository: not-fl3/macroquad master <- head repository: adsick/macroquad my_new_branch`. Add some description and verify that the set of changes is correct. Press `Create Pull Request` button.
8.  Be patient, wait for review and fix any issues with your code. This is the hardest moment, but all the efforts will be eventually rewarded.

There are a lot of info missing in this mini-guide, so feel free to google something you don't understand or [create a new issue](https://github.com/not-fl3/macroquad/issues/new) and ask there.

Cheers

**Comment by adsick** [comment]
Huge thanks, @vitvakatu

**Pull request closed without merging**
