### PR TITLE
Add Raw Mouse Motion Event Support

### LINKED ISSUE #129: Constrain Mouse To Window (For First Person Camera infinite mouse scrolling)
I'm trying to get a first person 3D camera to work. Currently, I can successfully fly around the world and look using the mouse.

However, when the mouse reaches the edge of the screen, it hits the edge and no longer gives any mouse position information.

There are 2 ways to solve this that I can see:

1. Keep sending mouse events when mouse is outside the window.
2. Allow the user to set the mouse position so they can control wrapping the mouse when it goes outside the window.

I don't know if Sokol uses GLFW but in Raylib (GLFW), I have this same problem on Linux. Not quite sure how to solve it without a way to set the cursor position.

Note: I have used the `ctx.set_cursor_grab(true)` and `ctx.show_mouse(false)` functions and it doesn't change the above behavior.

Alternatively, if another 3D example could be created that tests the mouse look and screen border interaction that would be amazing.

Here is what I've got so far for reference:

```rust
use macroquad::prelude::*;
// use glam::vec3;

const MOVE_SPEED: f32 = 0.1;
const LOOK_SPEED: f32 = 0.1;


fn conf() -> Conf
{
    Conf {
        window_title: String::from("Macroquad"),
        window_width: 1260,
        window_height: 768,
        fullscreen: true,
        ..Default::default()
    }
}

#[macroquad::main(conf)]
async fn main() {
    let InternalGlContext { quad_context: ctx, ..} = unsafe { get_internal_gl() };

    ctx.show_mouse(false);
    ctx.set_cursor_grab(true);

    let dirt = load_texture("Dirt.png").await;
    dirt.set_filter(ctx, FilterMode::Nearest);

    let mut x = 0.0;
    let mut switch = false;
    let bounds = 8.0;


    let world_up = vec3(0.0, 1.0, 0.0);
    let mut yaw: f32 = 0.0;
    let mut pitch: f32 = 0.0;

    let mut facing = vec3(
        yaw.cos() * 1.0,
        0.0,
        yaw.sin() * 1.0
    ).normalize();

    let mut front = vec3(
        yaw.cos() * pitch.cos(),
        pitch.sin(),
        yaw.sin() * pitch.cos()
    ).normalize();
    let mut right = front.cross(world_up).normalize();
    let mut up;

    let mut position = vec3(0.0, 1.0, 0.0);
    let mut last_mouse_position: Vec2 = mouse_position().into();

    let mut own_mouse_position = vec2(0.0, 0.0);

    loop {
        let delta = get_frame_time();
        
        if is_key_pressed(KeyCode::Escape) { break; }

        if is_key_down(KeyCode::Up) { position += front * MOVE_SPEED; }
        if is_key_down(KeyCode::Down) { position -= front * MOVE_SPEED; }
        if is_key_down(KeyCode::Left) { position -= right * MOVE_SPEED; }
        if is_key_down(KeyCode::Right) { position += right * MOVE_SPEED; }

        let mouse_position: Vec2 = mouse_position().into();
        let mouse_delta = mouse_position - last_mouse_position;
        last_mouse_position = mouse_position;

        yaw += mouse_delta.x * delta * LOOK_SPEED;
        pitch += mouse_delta.y * delta * -LOOK_SPEED;

        pitch = if pitch > 1.5 { 1.5 } else { pitch };
        pitch = if pitch < -1.5 { -1.5 } else { pitch };

        facing = vec3(
            yaw.cos() * 1.0,
            0.0,
            yaw.sin() * 1.0
        ).normalize();
    
        front = vec3(
            yaw.cos() * pitch.cos(),
            pitch.sin(),
            yaw.sin() * pitch.cos()
        ).normalize();

        right = front.cross(world_up).normalize();
        up = right.cross(front).normalize();


        x += if switch { 0.04 } else { -0.04 };
        if x >= bounds || x <= -bounds { switch = !switch; }

        clear_background(Color::new(1.0, 0.7, 0.0, 1.0));

        // Going 3d!

        set_camera(Camera3D {
            position: position,
            up: up,
            target: position + front,
            ..Default::default()
        });

        draw_grid(20, 1.);

        draw_line_3d(vec3(x, 0.0, x), vec3(5.0, 5.0, 5.0), Color::new(1.0, 1.0, 0.0, 1.0));

        draw_cube_wires(vec3(0., 1., -6.), vec3(2., 2., 2.), DARKGREEN);
        draw_cube_wires(vec3(0., 1., 6.), vec3(2., 2., 2.), DARKBLUE);
        draw_cube_wires(vec3(2., 1., 2.), vec3(2., 2., 2.), YELLOW);

        draw_cube(vec3(x, 1., x), vec3(2., 2., 2.), dirt, WHITE);

        // Back to screen space, render some text

        set_default_camera();
        draw_text("WELCOME TO 3D WORLD", 10.0, 20.0, 30.0, BLACK);

        draw_text(format!("X: {} Y: {}", own_mouse_position.x, own_mouse_position.y).as_str(), 10.0, 48.0, 30.0, BLACK);
        draw_text(format!("X: {} Y: {}", mouse_position.x, mouse_position.y).as_str(), 10.0, 48.0 + 18.0, 30.0, BLACK);

        next_frame().await
    }
}
```

### PR DESCRIPTION
**Pull request by Pebaz**
# This is a draft PR

Fix #129 

* Adds support for grabbing mouse cursor.
* Adds FPS example for use with new functions.
* Re-exports `set_cursor_grab` and `show_mouse` from Miniquad.

### CODE REVIEW

**Comment by Pebaz** [comment]
@not-fl3 Please review and let me know what I can improve or change.

Before you continue though, **this PR does not currently work** because I need some information. Although I think the changes to be complete, they do not currently work due to what I believe to be a missing feature in Miniquad (but I could be wrong).

Currently, I have these problems:

1. The new changes do not work on Windows because absolute mouse events are not handled by Miniquad on Windows yet. Please see these two links for details:
  * https://github.com/not-fl3/miniquad/issues/165
  * https://github.com/not-fl3/miniquad/issues/139
  * https://github.com/not-fl3/miniquad/blob/763cc21f41467b2af869d9d29c12d5c2a2d5e716/native/sapp-windows/src/lib.rs#L766
2. The `set_cursor_grab` function in Miniquad just does not capture the mouse on Linux or Windows. I even went and combed through the [tinyFPS project](https://github.com/cedric-h/minifps) to see if I was doing anything differently and I am not. For some reason, tinyFPS is successfully able to capture the mouse (using Miniquad), but these new changes that call into Miniquad are not properly capturing the mouse.

Let me know how I can help! 🙂

**Comment by not-fl3** [comment]
I did not quite get it - you got that panic on windows, while the tinyfps works perfectly?

**Comment by Pebaz** [comment]
Not quite, on Windows, it doesn't ever update the mouse coordinates on Windows when the mouse is captured. On Linux, it does send raw mouse events and the mouse coordinates update, but the mouse is still not captured (prevented from leaving the window).

You can test it by putting a println in the raw_mouse_motion function. On Windows it won't ever print, on Linux it prints but the mouse is not constrained to the window.

TinyFPS works correctly, but I can't imagine how, since Miniquad doesn't have absolute mouse events...?

**Comment by Pebaz** [comment]
I should also specify that both platforms don't prevent the mouse from leaving. 🤷‍♂️

**Comment by not-fl3** [comment]
I am happy that tinyfps works, so it should be fixable, will look into this later :)

**Comment by Pebaz** [comment]
Ok sounds good! :)

**Pull request closed without merging**
