### PR TITLE
FIX: text drawing was broken! 

### PR DESCRIPTION
**Pull request by bbogdan-ov**
Im really sorry, but i just found out that i screwed up with `total_width` calculation order in `draw_text_ex` (#776)

Please merge this pull request, because i made a terrible mistake...

### CODE REVIEW

**Comment by not-fl3** [comment]
No worries, I should've reviewit better :) 

Could you please rebase it tho?

**Comment by bbogdan-ov** [comment]
But how could i do that? Didn't i already fixed conflicts?
Sorry if it was a stupid question

**Comment by not-fl3** [comment]
> But how could i do that? Didn't i already fixed conflicts? Sorry if it was a stupid question

nevermind :) 
Ideally you want to rebase/squash your commits to have just one commit per one change, but its not really that important, I can squash them myself

**Comment by bbogdan-ov** [comment]
Thanks!

**Pull request merged**
