### PR TITLE
style: simplify some statements for readability

### LINKED ISSUE #872: Some statements can be simplified for readability
We can replace lines like

```rust
.expect(&format!(
    "Include file {} in not on \"includes\" list",
    filename
));
```

with

```rust
.expect(&format!(
    "Include file {filename} in not on \"includes\" list"
));
```

to improve code readability and maintainability.

### PR DESCRIPTION
**Pull request by hamirmahal**
Closes #872

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
`CI` passed on a fork.

**Comment by hamirmahal** [comment]
> `CI` passed on a fork.

https://github.com/hamirmahal/macroquad/actions/runs/12553047667

**Comment by hamirmahal** [comment]
> `CI` passed on a fork.

https://github.com/hamirmahal/macroquad/actions/workflows/rust.yml

**Comment by not-fl3** [comment]
thanks for PR!

**Comment by hamirmahal** [comment]
You're welcome!

**Pull request merged**
