### PR TITLE
Remove Collisions With Out-of-Bounds Tiles

### PR DESCRIPTION
**Pull request by zicklag**
A fix for https://github.com/fishfight/FishFight/issues/135.

I've only tested it with FishFight, but it appeared to fix the problem.

### CODE REVIEW

**Comment by not-fl3** [comment]
Goot catch, thanks!

**Comment by zicklag** [comment]
@not-fl3 would it be possible to get a new Crates.io release for `macroquad-platformer` with this change?

**Comment by not-fl3** [comment]
> @not-fl3 would it be possible to get a new Crates.io release for `macroquad-platformer` with this change?

Sure, `0.1.3` published

**Comment by zicklag** [comment]
Awesome, thanks!

**Pull request merged**
